### ISSUE TITLE
Compact mode bug

### ISSUE THREAD

**Issue by SkytAsul** [KorbsStudio/Aurora#3]
When using compact mode for text channels, usernames and messages are overlapping.

EDIT: I fixed it with this custom css:
```css
.messageContent-2qWWxC{
    margin-left: 0px !important;
}
```
